### PR TITLE
BonMot 4.0

### PR DESCRIPTION
**Pull request by KingOfBrian**
Hey folks
   Zev and I are looking for feedback on a Swift-first version of BonMot. The primary goals of the new version is a Swift-first API and Dynamic Type support for any font style. This PR is a WIP and contains the current state of the BonMot 4.0 API. This supports swift 2.2, 2.3 and 3.0. 

Simple Example:

``` swift
let trackingString = "Adults are always asking kids what they want to be when they grow up because they are looking for ideas.\n—Paula Poundstone"
    .styled(with: .tracking(.adobe(300)),
            .font(UIFont(name: "Avenir-Book", size: 18)!),
            .adapt(.control))
```

We chose to depart from BonMot's original chaining syntax, since chaining isn't very swifty. The new BonMot has a new Composition syntax that we hope will work just as nicely, and a bit more swifty:

``` swift
let colorString = NSAttributedString.composed(of: [
    "I want to be different. If everyone is wearing ",
    " black, ".styled(with: .color(.white),
                      .backgroundColor(.black),
                      .font(UIFont(name: "SuperClarendon-Black", size: 20)!)),
    " I want to be wearing ",
    " red. ".styled(with: .color(.white),
                    .backgroundColor(.raizlabsRed),
                    .font(UIFont(name: "SuperClarendon-Black", size: 20)!)),
    "\nMaria Sharapova ".styled(with: .color(.raizlabsRed),
                                .font(UIFont(name: "SuperClarendon-Black", size: 20)!)),
    UIImage(named: "Tennis Racket")!.styled(with:
        .color(.raizlabsRed), .baselineOffset(-4.0))
    ], baseStyle: .style(
        .font(UIFont(name: "GillSans-Light", size: 20)!),
        .lineHeightMultiple(1.8),
        .color(.darkGray)
    ))
```

However, from using BonMot in our projects, we realize that while this chaining API is nice, it is very painful to localize.  So, BonMot 4.0 adds support for styling arbitrary XML. We've tried to talk ourselves out of this many times now, but XML is actually great for this problem. The above string becomes:

``` swift
let content = "I want to be different. If everyone is wearing <black> black, </black> I want to be wearing <red> red. </red>\n<signed>Maria Sharapova</signed> <racket/>"
let racket = UIImage(named: "Tennis Racket")!.styled(with:
    .color(.raizlabsRed), .baselineOffset(-4.0))

let string = try? NSAttributedString.composed(
    ofXML: content,
    baseStyle: .style(
        .font(UIFont(name: "GillSans-Light", size: 20)!),
        .lineHeightMultiple(1.8),
        .color(.darkGray)),
    rules: [
        .style("black", .style(
            .color(.white),
            .backgroundColor(.black),
            .font(UIFont(name: "SuperClarendon-Black", size: 20)!)
            )),
        .style("red", .style(
            .color(.white),
            .backgroundColor(.raizlabsRed),
            .font(UIFont(name: "SuperClarendon-Black", size: 20)!)
            )),
        .style("signed", .style(
            .color(.raizlabsRed),
            .font(UIFont(name: "SuperClarendon-Black", size: 20)!)
            )),
        .enter(element: "racket", insert: racket)
    ]
)
```

And did we mention the above strings support Dynamic Type? It's as easy as that `.adapt(.control)` line!

Feel free to comment here on the PR for any other feedback, or help out on an [Issue](https://github.com/Raizlabs/BonMot/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0)

Thanks

Brian & Zev

### CODE REVIEW

**Comment by Imperiopolis** [comment]
Looking through your examples, I'm curious how the changed syntax would allow the most common case I have, a "styles" factory that vends things like h1, h2, body, caption, etc. to quickly setup common styles. Right now this looks something like the following for me:
```swift
struct Styles {
  static func h1 -> BONChain { 
    return BONChain().font(font).lineHeight(123).tagStyles(defaultStyles)
  }
}
```

And it's consumed something like the following allowing it to be quickly expanded upon with further styles.
```swift
let label = UILabel()
label.bonTextable = Styles.h1.alignment(.center).color(.blue).string("abc")
```

How would something like this work in the 4.0 world?

It seems like, looking at the `AdaptableTextContainer` stuff I could _mostly_ solve this by vending a `AttributedStringStyle`, but it doesn't seem like that has any knowledge of tag styles? Part of my usage is vending a set of base tags in each of the `BONChain`s I create right now so all text fields in the app support our tag system, since content is dynamically provided via the web and could arbitrarily have style changes like the addition of a `<strong></strong>` or such.

**Comment by KingOfBrian** [comment]
Hey, first off, awesome use case, it helps so much! One thing to call out is the most substantial change in 4.0 is the separation of style, content, and tags. Looking at this use case I see that 4.0 can use some improvement with the tagging integration, and let me sit on it for a few. Ignoring that elephant for the moment, it would look very similar:

```swift
struct Styles {
  static func h1 -> AttributedStringStyle { 
    return AttributedStringStyle(.font(font), .lineHeight(123))
  }
}
let label = UILabel()
label.bonMotStyle = Styles.h1.derive(.alignment(.center), .color(.blue))
label.styledText = "abc"
```

Now my vision for how tagging would work was a bit different, and is not integrated with the UIKit extensions (and it should be). So ignoring those, the simple tagging case would be like:
```
TagStyles.shared.registerStyle(forName:"h1", .style(.font(font), .lineHeight(123)))
TagStyles.shared.registerStyle(forName:"strong", .style(.font(font2)))

let label = UILabel()
label.attributedText =  NSAttributedString.composed(ofXML:"abc<bold>ABC</bold>", baseStyle: Styles.h1)
```

This is great feedback though, and a great use case. I'll push up something that supports this type of use case soon.

**Comment by leoneparise** [comment]
I tested the new API and it's awesome!! When will it come out?

**Comment by ZevEisenberg** [comment]
@leoneparise glad you like it! We're just wrapping up a couple of last minute details. I think there will probably be a beta 2 this weekend or early next week, and hopefully a launch soon after! Please open issues for any problems you find, because this is the big chance to make breaking changes.

**Pull request merged**
